version: 2

sources :
  - name : RAW
    database: DBT_RAW
    tables:
      - name: batdongsan_com_vn
      - name: 123nhadat
      - name: alonhadat
  - name: STAGING
    database: DBT_STAGING
  - name : MART
    database: DBT_MART